# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 666185e1c763121498cba0a4cddad20530d420a79c3cef3db4683878a76bb68fdb47d4e0f240c1c0aa87e40015994a2b8601f50d35bd9ecb6fb93160ad17de34

test:
  secret_key_base: 9210fa4a935d4685e7b394c741cce9928343af2d1ed8849ac84da9afd4d7f8178a2d51af74f66533b5c8aca7841af17346c354540b24a49bbddd01eefa3f67ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
